### ISSUE TITLE
Configurable title instead of "ldgallery". Plus dynamic title with current path.

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#149] opened 2020-02-25 01:19 UTC
The user should be able to configure his gallery's title (for better Bookmarks especially).
The title could go in config.json.

The viewer would use this title, followed by the current path or element's name.

**Comment by pacien** [comment] 2020-02-25 02:44
Actually that's a duplicate of #95.

**Closed by pacien** 2020-02-25 02:44 UTC
Labels: class:enhancement, component:compiler, component:viewer
